@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Jul 07 19:10:12 -0700 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 7a31fb4b03864c6e9c0a21bd6416bb24 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot test_5a_behav xil_defaultlib.test_5a -log elaborate.log"
call xelab  -wto 7a31fb4b03864c6e9c0a21bd6416bb24 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot test_5a_behav xil_defaultlib.test_5a -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
